Django_Blog/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"


urlpatterns = [
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addarticle/', views.addArticle, name = "addarticle"),
    path('article/<int:id>',views.detail, name = "detail"),
    path('update/<int:id>',views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle, name = "delete"),
    path('',views.articles, name = "articles"),
    path('comment/<int:id>',views.addComment, name = "comment"),
   
]

Django_Blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from article import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),

   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_Blog/user/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logout, name = "logout"),
]

Django_Blog/article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length = 50,verbose_name="Başlık")
    content = RichTextField(verbose_name="İçerik")
    created_date = models.DateTimeField(auto_now_add = True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True, verbose_name = "Makaleye fotoğraf ekleyin:")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["-created_date"]

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete= models.CASCADE, verbose_name = "Makale", related_name = "Comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "İsim")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ["-comment_date"]

Django_Blog/user/models.py
from django.db import models

# Create your models here.

Django_Blog/article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

Django_Blog/user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı")
    password = forms.CharField(label = "Parola", widget=forms.PasswordInput)
    
class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50, label = "Kullanıcı Adı")
    password = forms.CharField(max_length = 50, label = "Parola",widget= forms.PasswordInput)
    confirm = forms.CharField(max_length= 20, label = "Parolayı Onayla", widget= forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolar Eşleşmiyor")
        
        values = {
            "username" : username,
            "password" : password,
        }
        return values

Django_Blog/article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):

    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains =keyword )
        return render(request,"articles.html",{"articles":articles} )
    
    articles = Article.objects.all()

    return render(request, "articles.html", {"articles":articles})

def index(request):

    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        form.save()

        messages.success(request,"Makaleniz Kaydedildi")

        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})

def detail(request,id):
    #artcile = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)

    comments = article.Comments.all()

    return render(request, "detail.html",{"article": article, "comments": comments})

@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id = id)

    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        form.save()

        messages.success(request,"Makaleniz Güncellendi")

        return redirect("article:dashboard")

    return render(request, "update.html", {"form" : form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    
    article = get_object_or_404(Article, id = id)

    article.delete()

    messages.success(request, "Makale Başarıyla Silindi")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article, id = id)


    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content= comment_content)
        
        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

Django_Blog/user/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login as auth_login,authenticate
from django.contrib.auth import logout as auth_logout

from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@csrf_exempt
def register(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username = username)
        newUser.set_password(password)
           
        newUser.save()
        auth_login(request,newUser)
        messages.success(request,"Başarı ile kayıt olundu")
           
        return redirect("index")
       
    context = {
        "form" : form
        }
    return render(request,"register.html",context)


@csrf_exempt
def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username, password = password)

        if user is None:
            messages.info(request, "Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context) 
        
        messages.success(request,"Başarı ile giriş yaptınız...")
        auth_login(request,user)
        return redirect("index")
    return render(request,"login.html",context)

def logout(request):
    auth_logout(request)
    messages.success(request,"Hesaptan Çıkış Yapıldı.")
    return redirect("index")

Django_Blog/templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Hakkımızda</h3>
<hr>

<p>
    Erhan Erkut, lisans derecesini 1980’de Boğaziçi Üniversitesi Endüstri Mühendisliği Bölümünden, doktorasını ise 1986’da Florida Üniversitesi’nden aldı. 1985-2005 yıllarında Alberta Üniversitesi İşletme Fakültesinde ders veren Prof. Erkut bu dönemde “INFORMS Teaching of Management Science Practice Award” ile “3M Teaching Fellowship” başta olmak üzere dokuz eğitim ödülü ile Canadian Operational Research Society tarafından verilmiş beş başarı ödülü aldı, ve 50’den fazla hakemli dergi makalesi yayınladı.  Eğitim ve araştırmanın yanında birçok endüstriyel projeyi de yöneten Prof. Erkut, Centre for Excellence in Operations adlı bir uygulamalı araştırma merkezi kurdu, ve INFORMS Transactions in Education dergisinin kurucu editörlüğünü yaptı.

    2005’de Türkiye’ye dönen Prof. Erkut, 2005-07 arasında Bilkent Üniversitesi İşletme Fakültesi Dekanlığı, 2008-13 arasında Özyeğin Üniversitesi Rektörlüğü, 2014′den bu yana ise MEF Üniversitesi’nde Rektör Yardımcısı görevlerinde bulundu.  İstanbul Erkek Lisesi Eğitim Vakfı, Kariyer Planlama Derneği, ve Bilim Kahramanları derneklerinde yönetim kurulu üyeliği yapan Prof. Erkut, son yıllarda Türkiye’de girişimcilik ve yetkinlik gelişimi konularında aktif olarak çalışmaktadır. Erhan Erkut’un detaylı özgeçmişine bu linkten ulaşabilirsiniz.


</p>
{% endblock body %}<h3>Hakkımızda</h3>

Django_Blog/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">on
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kaydet</button>
        </form>

    </div>
</div>
{% endblock body %}

Django_Blog/templates/articles.html
{% extends "layout.html" %}

{% block body %}
<div class="col-lg-8">
<h3>Makaleler</h3>
<hr>
</div>

<div class="row">
    <div class="col-lg-8">
        <form>
            {% csrf_token %}
            <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
            <button type="submit" class="btn btn-danger">ARA</button>
        </form>
    </div>    
</div>

{% if articles %}
{% for article in articles %}
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h4 class="fw-bolder mb-1">{{article.title}}</h4></a>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2"><em><small>posted by {{article.author}}</small></em></div>
                <hr>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <img src="{{article.article_image.url}}" alt="{{article.title}}" /></figure>            
            {% endif %}
            
            
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content | safe | truncatewords:3}} <a href="{% url 'article:detail' article.id %}" button = "btn btn-danger">Devamını Oku</a>
                </p>
                
    
            </section>
        </article>
        
    </div>
    
</div>
{% endfor %}

{% else %}
<div class="col-lg-8">
    <div class = "alert alert-danger">
        Makale Bulunamadı...
    </div>
</div>
{% endif %}
{% endblock body %}

Django_Blog/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>Hoşgeldiniz, <strong>{{request.user.username}}</strong></p>
<br>
<a class="btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
<br>
<br>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
        <th scope="row">{{article.id}}</th>
        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
        <td>{{article.author}}</td>
        <td>{{article.created_date}}</td>
        <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
        <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
<div class = "alert alert-danger">
    Henüz bir makale eklemediniz...
</div>
{% endif %}

{% endblock body %}

Django_Blog/templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on {{article.created_date}} by {{article.author}}</div>
                <hr>
            </header>
            <!-- Preview image figure-->
            {% if article.article_image %}
            <img src="{{article.article_image.url}}" alt="{{article.title}}" /></figure>            
            {% endif %}
            
            
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content | safe}}
                </p>
                
    
            </section>
        </article>
        <hr>
        <br>
        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
        
        {% for comment in comments %}
        <div class="d-flex">
            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
            <div class="ms-3">
                <div class="fw-bold"> 
                    <h6>{{comment.comment_author}} </h6>
                    <small>{{comment.comment_date}}</small> <br> <br>
                    {{comment.comment_content}}
                </div>
                
                <br>
                <br>
            </div>
            
        </div>
        {% endfor %}

        {% else %}
        <div class = "alert alert-danger">
            Bu makaleye herhangi bir yorum yapılmamış, ilk yapan siz olun!
        </div>
        {% endif %}
        <section class="mb-5">
            <div class="card bg-light">
                <h6 class = "card-header">Yorum Ekle:</h6>
                <div class="card-body">
                    <!-- Comment form-->
                    <form method = "post" action = "{% url 'article:comment' article.id %}" class="mb-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">İsim</label>
                            <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi Yazınız">
                        </div>
                        <label for="formGroupExampleInput">Yorum</label>
                        <textarea name = "comment_content" class="form-control" rows="3" placeholder="Yorumunuzu Yazın..."></textarea>
                        <button type = "submit" class= "btn btn-danger">Ekle</button>
                    </form>
                    
                </div>
                
            </div>
                   
    </div>
    
    
</div>


{% endblock body %}

Django_Blog/templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'index' %}">YB Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
      </ul> 

      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
        </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}">Kayıt ol</a>
        </li>

      </ul> 
    </div>
  </nav>

Django_Blog/templates/includes/posttemplate.html
<div class="row">
    <div class="col-lg-8">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">Posted on January 1, 2023 by Start Bootstrap</div>
                <!-- Post categories-->
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
            </header>
            <!-- Preview image figure-->
            <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
            <!-- Post content-->
            <section class="mb-5">
                <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
            </section>
        </article>
        <!-- Comments section-->
        <section class="mb-5">
            <div class="card bg-light">
                <div class="card-body">
                    <!-- Comment form-->
                    <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                    <!-- Comment with nested comments-->
                    <div class="d-flex mb-4">
                        <!-- Parent comment-->
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                            <!-- Child comment 1-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                </div>
                            </div>
                            <!-- Child comment 2-->
                            <div class="d-flex mt-4">
                                <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                <div class="ms-3">
                                    <div class="fw-bold">Commenter Name</div>
                                    When you put money directly to a problem, it makes a good headline.
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Single comment-->
                    <div class="d-flex">
                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                        <div class="ms-3">
                            <div class="fw-bold">Commenter Name</div>
                            When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- Side widgets-->
    <div class="col-lg-4">
        <!-- Search widget-->
        <div class="card mb-4">
            <div class="card-header">Search</div>
            <div class="card-body">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                    <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                </div>
            </div>
        </div>
        <!-- Categories widget-->
        <div class="card mb-4">
            <div class="card-header">Categories</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li><a href="#!">Web Design</a></li>
                            <li><a href="#!">HTML</a></li>
                            <li><a href="#!">Freebies</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6">
                        <ul class="list-unstyled mb-0">
                            <li><a href="#!">JavaScript</a></li>
                            <li><a href="#!">CSS</a></li>
                            <li><a href="#!">Tutorials</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Side widget-->
        <div class="card mb-4">
            <div class="card-header">Side Widget</div>
            <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
        </div>
    </div>
</div>

Django_Blog/templates/index.html
{% extends "layout.html" %}

{% block body %}

<div style="margin-top : 100px;"  class="jumbotron text-center">
    <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogda dünya ve insanları anlamaya çalışırken aklımdan geçenleri sizlerle paylaşacağım.</p>
</div>

<p>
    {% if request.user.is_authenticated %}
        Giriş Yapılmış,{{request.user.username}}
    {% else %}
        Giriş Yapılmamış
    {% endif %}
</p>


{% endblock body %}

Django_Blog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>YbBlog</title>
</head>
<body>
    
    {% include "includes/navbar.html" %}
    <div style = "margin-bottom: 100px;" class = "container">
        {% if messages %}
               
                        {% for message in messages %}
                        {% if tags == "info" %}
                        <div class="alert alert-danger">{{ message }}</div>
                        {% else %}
                        <div class="alert alert-{{ message.tags }} ">{{ message }}</div>
                        {% endif %}
                        
                        {% endfor %}
                
        {% endif %}
        {% block body %}
        

        {% endblock body %}
    


    </div>
    





    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

</body>
</html>

Django_Blog/templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form form method = "POST">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
        </form>

    </div>
</div>

{% endblock body %}

Django_Blog/templates/logout.html
{% extends "layout.html" %}

{% block body %}

<h3>Çıkış Yap</h3>
<hr>

{% endblock body %}

Django_Blog/templates/register.html
{% extends "layout.html" %}

{% block body %}

<h3>Kayıt Ol</h3>
<hr>

<form method = "post">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <button type ="submit" class="btn btn-danger">Kayıt Ol</button>
    
</form>
{% endblock body %}

Django_Blog/templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="POST" enctype="multipart/form-data">on
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Güncelle</button>
        </form>

    </div>
</div>
{% endblock body %}